import { Router, Response } from 'express';
import { authenticate, AuthRequest } from '../middleware/auth';
import prisma from '../utils/prisma';
import { createAlert, runAllScans } from '../utils/alert-engine';
const router = Router();
router.use(authenticate);

// List alerts
router.get('/', async (req: AuthRequest, res: Response) => {
  try {
    const { type, severity, isResolved, page = '1', limit = '30' } = req.query as any;
    const where: any = {};
    if (type) where.type = type;
    if (severity) where.severity = severity;
    if (isResolved !== undefined) where.isResolved = isResolved === 'true';
    const skip = (Number(page) - 1) * Number(limit);
    const [alerts, total] = await Promise.all([
      prisma.alert.findMany({ where, skip, take: Number(limit), orderBy: { createdAt: 'desc' } }),
      prisma.alert.count({ where }),
    ]);
    return res.json({ alerts, total });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Alert summary (counts by severity)
router.get('/summary', async (req: AuthRequest, res: Response) => {
  try {
    const [critical, urgent, warning, info, unresolved, total] = await Promise.all([
      prisma.alert.count({ where: { severity: 'critical', isResolved: false } }),
      prisma.alert.count({ where: { severity: 'urgent', isResolved: false } }),
      prisma.alert.count({ where: { severity: 'warning', isResolved: false } }),
      prisma.alert.count({ where: { severity: 'info', isResolved: false } }),
      prisma.alert.count({ where: { isResolved: false } }),
      prisma.alert.count(),
    ]);
    return res.json({ critical, urgent, warning, info, unresolved, total });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Get single alert
router.get('/:id', async (req: AuthRequest, res: Response) => {
  try {
    const alert = await prisma.alert.findUnique({ where: { id: req.params.id } });
    if (!alert) return res.status(404).json({ error: 'Not found' });
    return res.json({ alert });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Create manual alert
router.post('/', async (req: AuthRequest, res: Response) => {
  try {
    const { type, severity, title, message, entityType, entityId, assignedTo, dueAt } = req.body;
    if (!type || !title || !message)
      return res.status(400).json({ error: 'type, title, message required' });

    const alert = await createAlert({
      type, severity: severity || 'warning', title, message,
      entityType, entityId, assignedTo,
      dueAt: dueAt ? new Date(dueAt) : undefined,
      autoGenerated: false,
    });
    return res.status(201).json({ alert });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Resolve alert
router.put('/:id/resolve', async (req: AuthRequest, res: Response) => {
  try {
    const { note } = req.body;
    const alert = await prisma.alert.update({
      where: { id: req.params.id },
      data: { isResolved: true, resolvedBy: req.user?.id, resolvedAt: new Date(), resolvedNote: note || null },
    });
    return res.json({ alert });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Assign alert
router.put('/:id/assign', async (req: AuthRequest, res: Response) => {
  try {
    const { assignedTo, dueAt } = req.body;
    const data: any = {};
    if (assignedTo !== undefined) data.assignedTo = assignedTo;
    if (dueAt) data.dueAt = new Date(dueAt);
    const alert = await prisma.alert.update({ where: { id: req.params.id }, data });
    return res.json({ alert });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Bulk resolve
router.put('/bulk-resolve', async (req: AuthRequest, res: Response) => {
  try {
    const { ids, note } = req.body;
    if (!ids || !Array.isArray(ids)) return res.status(400).json({ error: 'ids array required' });
    await prisma.alert.updateMany({
      where: { id: { in: ids } },
      data: { isResolved: true, resolvedBy: req.user?.id, resolvedAt: new Date(), resolvedNote: note || null },
    });
    return res.json({ message: `${ids.length} alerts resolved` });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Run alert scan
router.post('/scan', async (req: AuthRequest, res: Response) => {
  try {
    const result = await runAllScans();
    // Audit log
    await prisma.auditLog.create({ data: {
      userId: req.user?.id, action: 'alert_scan', entityType: 'alert',
      entityId: 'scan', details: JSON.stringify(result),
    }});
    return res.json(result);
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// ─── ALERT RULES ──────────────────────────────────────────

// List rules
router.get('/rules/list', async (req: AuthRequest, res: Response) => {
  try {
    const rules = await prisma.alertRule.findMany({ orderBy: { type: 'asc' } });
    return res.json({ rules });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Update rule
router.put('/rules/:id', async (req: AuthRequest, res: Response) => {
  try {
    const data: any = {};
    for (const f of ['description', 'severity', 'thresholdUnit'])
      if (req.body[f] !== undefined) data[f] = req.body[f];
    if (req.body.thresholdValue !== undefined) data.thresholdValue = Number(req.body.thresholdValue);
    if (req.body.isActive !== undefined) data.isActive = req.body.isActive;
    const rule = await prisma.alertRule.update({ where: { id: req.params.id }, data });
    return res.json({ rule });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

// Seed default rules
router.post('/rules/seed', async (req: AuthRequest, res: Response) => {
  try {
    const defaults = [
      { type: 'delayed_loading', description: 'Trip dispatched but not loading', thresholdValue: 4, thresholdUnit: 'hours', severity: 'warning' },
      { type: 'delayed_delivery', description: 'Trip in transit beyond threshold', thresholdValue: 24, thresholdUnit: 'hours', severity: 'urgent' },
      { type: 'missing_pod', description: 'Trip completed without POD upload', thresholdValue: 3, thresholdUnit: 'days', severity: 'warning' },
      { type: 'qty_mismatch', description: 'Shortage exceeds threshold percentage', thresholdValue: 5, thresholdUnit: 'percent', severity: 'urgent' },
      { type: 'repeated_breakdown', description: 'Vehicle with multiple breakdowns', thresholdValue: 3, thresholdUnit: 'count', severity: 'warning' },
      { type: 'expired_docs', description: 'Vehicle documents expired', thresholdValue: 0, thresholdUnit: 'days', severity: 'critical' },
      { type: 'cash_variance', description: 'Cash session variance above threshold', thresholdValue: 100, thresholdUnit: 'ETB', severity: 'urgent' },
      { type: 'overdue_invoice', description: 'Invoice past due date', thresholdValue: 0, thresholdUnit: 'days', severity: 'warning' },
    ];

    const results = [];
    for (const d of defaults) {
      const rule = await prisma.alertRule.upsert({
        where: { type: d.type },
        update: {},
        create: { ...d, isActive: true },
      });
      results.push(rule);
    }
    return res.json({ rules: results, count: results.length });
  } catch (e: any) { return res.status(500).json({ error: e.message }); }
});

export default router;
