import prisma from './prisma';
import { sendNotification } from './telegram';

/**
 * Create an alert if one doesn't already exist for the same entity + type (unresolved)
 */
export async function createAlert(data: {
  type: string;
  severity: string;
  title: string;
  message: string;
  entityType?: string;
  entityId?: string;
  assignedTo?: string;
  dueAt?: Date;
  autoGenerated?: boolean;
}): Promise<any> {
  // Check for existing unresolved alert of same type for same entity
  if (data.entityType && data.entityId) {
    const existing = await prisma.alert.findFirst({
      where: { type: data.type, entityType: data.entityType, entityId: data.entityId, isResolved: false },
    });
    if (existing) return existing; // Don't duplicate
  }

  const alert = await prisma.alert.create({
    data: {
      type: data.type,
      severity: data.severity,
      title: data.title,
      message: data.message,
      entityType: data.entityType || null,
      entityId: data.entityId || null,
      assignedTo: data.assignedTo || null,
      dueAt: data.dueAt || null,
      autoGenerated: data.autoGenerated !== undefined ? data.autoGenerated : true,
    },
  });

  // Send Telegram for critical/urgent alerts with proper category mapping
  if (data.severity === 'critical' || data.severity === 'urgent') {
    const categoryMap: Record<string, any> = {
      'delayed_loading': 'trip', 'delayed_delivery': 'trip', 'missing_pod': 'trip',
      'qty_mismatch': 'trip', 'repeated_breakdown': 'breakdown', 'expired_docs': 'compliance',
      'cash_variance': 'system', 'overdue_invoice': 'order',
    };
    const cat = categoryMap[data.type] || 'system';
    const level = data.severity === 'critical' ? 'critical' : 'urgent';
    sendNotification(level as any, cat, data.title, data.message).catch(() => {});
  }

  return alert;
}

/**
 * Run all alert scans — returns summary of created alerts
 */
export async function runAllScans(): Promise<{ scanned: string[]; alertsCreated: number; details: any[] }> {
  const details: any[] = [];
  let alertsCreated = 0;
  const scanned: string[] = [];

  // Get active rules
  const rules = await prisma.alertRule.findMany({ where: { isActive: true } });
  const ruleMap: any = {};
  rules.forEach(r => { ruleMap[r.type] = r; });

  // 1. Delayed Loading — trips dispatched but not loading within threshold hours
  if (ruleMap['delayed_loading']) {
    scanned.push('delayed_loading');
    const thresholdHours = ruleMap['delayed_loading'].thresholdValue || 4;
    const cutoff = new Date(Date.now() - thresholdHours * 3600000);
    const delayed = await prisma.trip.findMany({
      where: { status: 'dispatched', dispatchedAt: { lt: cutoff } },
      select: { id: true, tripNumber: true, dispatchedAt: true, vehicleId: true },
    });
    for (const trip of delayed) {
      const a = await createAlert({
        type: 'delayed_loading', severity: ruleMap['delayed_loading'].severity,
        title: `Delayed Loading: ${trip.tripNumber}`,
        message: `Trip ${trip.tripNumber} was dispatched ${Math.round((Date.now() - new Date(trip.dispatchedAt!).getTime()) / 3600000)}h ago but hasn't started loading`,
        entityType: 'trip', entityId: trip.id,
      });
      if (a) alertsCreated++;
    }
    details.push({ scan: 'delayed_loading', found: delayed.length });
  }

  // 2. Delayed Delivery — trips in_transit for too long
  if (ruleMap['delayed_delivery']) {
    scanned.push('delayed_delivery');
    const thresholdHours = ruleMap['delayed_delivery'].thresholdValue || 24;
    const cutoff = new Date(Date.now() - thresholdHours * 3600000);
    const delayed = await prisma.trip.findMany({
      where: { status: 'in_transit', departureTime: { lt: cutoff } },
      select: { id: true, tripNumber: true, departureTime: true },
    });
    for (const trip of delayed) {
      const hours = Math.round((Date.now() - new Date(trip.departureTime!).getTime()) / 3600000);
      await createAlert({
        type: 'delayed_delivery', severity: ruleMap['delayed_delivery'].severity,
        title: `Delayed Delivery: ${trip.tripNumber}`,
        message: `Trip ${trip.tripNumber} has been in transit for ${hours}h (threshold: ${thresholdHours}h)`,
        entityType: 'trip', entityId: trip.id,
      });
      alertsCreated++;
    }
    details.push({ scan: 'delayed_delivery', found: delayed.length });
  }

  // 3. Missing POD — completed trips without POD upload after threshold days
  if (ruleMap['missing_pod']) {
    scanned.push('missing_pod');
    const thresholdDays = ruleMap['missing_pod'].thresholdValue || 3;
    const cutoff = new Date(Date.now() - thresholdDays * 86400000);
    const missing = await prisma.trip.findMany({
      where: { status: 'completed', podUrl: null, unloadingEndTime: { lt: cutoff } },
      select: { id: true, tripNumber: true, unloadingEndTime: true },
    });
    for (const trip of missing) {
      const days = Math.round((Date.now() - new Date(trip.unloadingEndTime!).getTime()) / 86400000);
      await createAlert({
        type: 'missing_pod', severity: ruleMap['missing_pod'].severity,
        title: `Missing POD: ${trip.tripNumber}`,
        message: `Trip ${trip.tripNumber} completed ${days} days ago without POD upload`,
        entityType: 'trip', entityId: trip.id,
      });
      alertsCreated++;
    }
    details.push({ scan: 'missing_pod', found: missing.length });
  }

  // 4. Quantity Mismatch — trips with significant shortage
  if (ruleMap['qty_mismatch']) {
    scanned.push('qty_mismatch');
    const thresholdPercent = ruleMap['qty_mismatch'].thresholdValue || 5; // % shortage
    const recent = await prisma.trip.findMany({
      where: { status: 'completed', shortage: { gt: 0 }, updatedAt: { gt: new Date(Date.now() - 7 * 86400000) } },
      select: { id: true, tripNumber: true, loadedQuantityTons: true, deliveredQuantityTons: true, shortage: true },
    });
    for (const trip of recent) {
      const loaded = trip.loadedQuantityTons || 1;
      const pct = ((trip.shortage || 0) / loaded) * 100;
      if (pct >= thresholdPercent) {
        await createAlert({
          type: 'qty_mismatch', severity: ruleMap['qty_mismatch'].severity,
          title: `Qty Mismatch: ${trip.tripNumber}`,
          message: `Trip ${trip.tripNumber} shortage: ${(trip.shortage || 0).toFixed(2)} tons (${pct.toFixed(1)}% of loaded)`,
          entityType: 'trip', entityId: trip.id,
        });
        alertsCreated++;
      }
    }
    details.push({ scan: 'qty_mismatch', found: recent.length });
  }

  // 5. Repeated Breakdown — vehicles with 3+ work orders in last 30 days
  if (ruleMap['repeated_breakdown']) {
    scanned.push('repeated_breakdown');
    const threshold = ruleMap['repeated_breakdown'].thresholdValue || 3;
    const cutoff = new Date(Date.now() - 30 * 86400000);
    const vehicles = await prisma.vehicle.findMany({
      where: { status: { not: 'inactive' } },
      select: { id: true, plateNumber: true },
    });
    for (const v of vehicles) {
      const woCount = await prisma.workOrder.count({
        where: { vehicleId: v.id, createdAt: { gt: cutoff } },
      });
      if (woCount >= threshold) {
        await createAlert({
          type: 'repeated_breakdown', severity: ruleMap['repeated_breakdown'].severity,
          title: `Repeated Breakdown: ${v.plateNumber}`,
          message: `Vehicle ${v.plateNumber} has had ${woCount} work orders in the last 30 days`,
          entityType: 'vehicle', entityId: v.id,
        });
        alertsCreated++;
      }
    }
    details.push({ scan: 'repeated_breakdown', found: vehicles.length });
  }

  // 6. Expired Documents — compliance check
  if (ruleMap['expired_docs']) {
    scanned.push('expired_docs');
    const now = new Date();
    const vehicles = await prisma.vehicle.findMany({
      where: { status: { not: 'inactive' }, complianceLocked: false },
      select: { id: true, plateNumber: true, insuranceExpiry: true, inspectionExpiry: true, permitExpiry: true },
    });
    for (const v of vehicles) {
      const expired: string[] = [];
      if (v.insuranceExpiry && new Date(v.insuranceExpiry) < now) expired.push('insurance');
      if (v.inspectionExpiry && new Date(v.inspectionExpiry) < now) expired.push('inspection');
      if (v.permitExpiry && new Date(v.permitExpiry) < now) expired.push('permit');
      if (expired.length > 0) {
        await createAlert({
          type: 'expired_docs', severity: ruleMap['expired_docs'].severity,
          title: `Expired Docs: ${v.plateNumber}`,
          message: `Vehicle ${v.plateNumber} has expired: ${expired.join(', ')}`,
          entityType: 'vehicle', entityId: v.id,
        });
        alertsCreated++;
      }
    }
    details.push({ scan: 'expired_docs', found: vehicles.length });
  }

  // 7. Cash Variance — sessions closed with variance above threshold
  if (ruleMap['cash_variance']) {
    scanned.push('cash_variance');
    const thresholdETB = ruleMap['cash_variance'].thresholdValue || 100;
    const recent = await prisma.cashierSession.findMany({
      where: { status: { in: ['closed', 'reconciled'] }, variance: { not: null }, closedAt: { gt: new Date(Date.now() - 7 * 86400000) } },
      include: { cashier: { select: { name: true } } },
    });
    for (const s of recent) {
      if (Math.abs(s.variance || 0) >= thresholdETB) {
        await createAlert({
          type: 'cash_variance', severity: ruleMap['cash_variance'].severity,
          title: `Cash Variance: ${(s as any).cashier?.name}`,
          message: `Cashier ${(s as any).cashier?.name} session on ${s.sessionDate} has variance of ETB ${(s.variance || 0).toFixed(2)}`,
          entityType: 'cashier', entityId: s.cashierId,
        });
        alertsCreated++;
      }
    }
    details.push({ scan: 'cash_variance', found: recent.length });
  }

  // 8. Overdue Invoices — unpaid invoices past due date
  if (ruleMap['overdue_invoice']) {
    scanned.push('overdue_invoice');
    const now = new Date();
    const overdue = await prisma.invoice.findMany({
      where: { status: { in: ['sent', 'overdue'] }, dueDate: { lt: now }, balanceDue: { gt: 0 } },
      include: { customer: { select: { companyName: true } } },
    });
    for (const inv of overdue) {
      const days = Math.round((now.getTime() - new Date(inv.dueDate!).getTime()) / 86400000);
      await createAlert({
        type: 'overdue_invoice', severity: days > 30 ? 'critical' : ruleMap['overdue_invoice'].severity,
        title: `Overdue Invoice: ${inv.invoiceNumber}`,
        message: `Invoice ${inv.invoiceNumber} for ${(inv as any).customer?.companyName} is ${days} days overdue (ETB ${inv.balanceDue.toFixed(2)})`,
        entityType: 'invoice', entityId: inv.id,
      });
      alertsCreated++;
    }
    details.push({ scan: 'overdue_invoice', found: overdue.length });
  }

  return { scanned, alertsCreated, details };
}
